spring:
  #配置连接池
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/blog?serverTimezone=Asia/Shanghai
      username: root
      password: root
      initial-size: 5
      min-idle: 5
      max-active: 5
      max-wait: 30000
      filter:
        stat:
          enabled: true
      filters: stat,wall,config
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: /druid/*,*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico
        session-stat-enable: true
        session-stat-max-count: 10
      stat-view-servlet:
        enabled: true #是否启用StatViewServlet默认值true
        url-pattern: /druid/*
        reset-enable: true
        login-username: admin
        login-password: admin
  #国际化信息
  messages:
    basename: i18n.page
  #禁用thymeleaf缓存
  thymeleaf:
    cache: false
  #启用hiddenMethodFilter
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true