spring:
  #配置连接池
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/blog?serverTimezone=Asia/Shanghai
      username: root
      password: root
      initial-size: 5
      min-idle: 5
      max-active: 5
      max-wait: 30000
  #国际化信息
  messages:
    basename: i18n.page
  #禁用thymeleaf缓存
  thymeleaf:
    cache: false